accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('login/', views.loginView, name="login"),
    path('logout/', views.logoutView),
    path('profile/', views.profileView),
    path('profileRegister/', views.profileRegisterView),
    path('profileEdit/', views.ProfileEditView),

]

concert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ticketSales.views import concertListView,locationListView,concertDetailsView,timeView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticketSales/',include('ticketSales.urls')),
    path('accounts/',include('accounts.urls'))


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ProfileModel(models.Model):
    class Meta:
        verbose_name="کاربر"
        verbose_name_plural="کاربر"

    user= models.OneToOneField(User,on_delete=models.CASCADE, verbose_name="کاربری", related_name="profile")   

    # Name= models.CharField(max_length=100,verbose_name="نام")
    # Family= models.CharField(max_length=100,verbose_name="نام خانوادگی")
    ProfileImage= models.ImageField(upload_to="ProfileImages/",verbose_name="عکس")

    
    Man=1
    Woman=2
    status_choices=((Man,"مرد"),(Woman,"زن"))

    Gender= models.IntegerField(choices=status_choices,verbose_name="جنسیت")
    Credit= models.IntegerField(verbose_name="اعتبار", default=0)    
    

    

accounts/forms.py
from django import forms
from accounts.models import ProfileModel
from django.contrib.auth.forms import UserChangeForm
from django.forms import fields


class ProfileRegisterForm(forms.ModelForm):
    first_name= forms.CharField(max_length=100)
    last_name= forms.CharField(max_length=100)
    username= forms.CharField(max_length=100)
    password= forms.CharField(widget=forms.PasswordInput)
    email= forms.CharField(widget=forms.EmailInput)

    class Meta:
        model=ProfileModel
        fields=['ProfileImage' , 'Credit' , 'Gender']


class ProfileEditForm(forms.ModelForm):

    class Meta:
        model=ProfileModel
        fields=['ProfileImage' , 'Credit' , 'Gender']

class UserEditForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields=["first_name", "last_name", "email"]
    password=None          

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
import ticketSales
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from accounts.forms import ProfileRegisterForm, ProfileEditForm,UserEditForm
from accounts.models import ProfileModel
from django.contrib.auth.models import User
import accounts


# Create your views here.
def loginView(request):
    #POST
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user=authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            if request.GET.get('next'):
                return HttpResponseRedirect(request.GET.get("next"))
            
            return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
                          
        else:
            context={
                "username":username,
                "errorMessage":"!کاربری با این مشخصات یافت نشد"
            }
            return render(request, "accounts/login.html" ,context)
    #GET
    else:
        return render(request, "accounts/login.html" , {})
    
def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse(ticketSales.views.concertListView))

@login_required
def profileView(request):
    profile=request.user.profile
    context={
        "profile":profile
    }
    return render(request,"accounts/profile.html", context)


def profileRegisterView(request):
    
    if request.method=="POST":
        profileRegisterForm=ProfileRegisterForm(request.POST,request.FILES)
        if profileRegisterForm.is_valid():

            user = User.objects.create_user(
                username=profileRegisterForm.cleaned_data["username"],
                email=profileRegisterForm.cleaned_data['email'],                         
                password=profileRegisterForm.cleaned_data['password'],
                first_name=profileRegisterForm.cleaned_data['first_name'],
                last_name=profileRegisterForm.cleaned_data['last_name'])
            
            user.save()

            profileModel= ProfileModel(user=user ,
                                       ProfileImage=profileRegisterForm.cleaned_data['ProfileImage'],
                                       Gender=profileRegisterForm.cleaned_data['Gender'],
                                       Credit=profileRegisterForm.cleaned_data['Credit'])
            profileModel.save()

            return HttpResponseRedirect(reverse(ticketSales.views.concertListView))
        
    else:
        profileRegisterForm= ProfileRegisterForm()

    context={
        "formData" : profileRegisterForm
    } 

    return render(request,"accounts/profileRegister.html",context)   


def ProfileEditView(request):
    if request.method=="POST":
        profileEditForm=ProfileEditForm(request.POST,request.FILES,instance=request.user.profile)
        userEditForm=UserEditForm(request.POST, instance=request.user)
        if profileEditForm.is_valid and userEditForm.is_valid:
            profileEditForm.save()
            userEditForm.save()
            return HttpResponseRedirect(reverse(accounts.views.profileView))
        
    else:
        profileEditForm=ProfileEditForm(instance=request.user.profile)
        userEditForm=UserEditForm(instance=request.user)

    context={
        "profileEditForm": profileEditForm,
        "userEditForm":userEditForm,
        "ProfileImage":request.user.profile.ProfileImage,
    }   
    return render(request, "accounts/profileEdit.html", context) 

accounts/templates/accounts/login.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
    ورود کاربران
{% endblock%}

{% block mainContent %}

    <div class="col-md-3"></div>
        <div class="col-md-6">
            <form action="" method="POST" class="form">
                {% csrf_token %}
                <h3>لطفا اطلاعات کاربری خود را وارد نمایید :</h3>
                <p style="color: red;">{{ username}} {{errorMessage}}</p>
                <label class="label-control">نام کاربری</label>
                <input type="text" id="username" name="username" placeholder="نام کاربری خود را وارد نمایید" class="form-control">
                <label class="label-control">رمز عبور </label>  
                <input type="password" id="password" name="password" placeholder="رمز عبور خود را وارد نمایید" class="form-control">
                <br>
                <input type="submit" value="ورود" class="btn btn-success">
            </form>
        
    
        </div> 
    <div class="col-md-3"></div>

{% endblock %}   

accounts/templates/accounts/profile.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
   پروفایل {{concertdetails.Name}}
{% endblock%}

{% block mainContent %}
    <div class="row">
        <div class="profBlock">
            <div class="prof-border">
                <p class="pStyle"> <span class="title">نام و نام خانوادگی : </span>{{profile.user.get_full_name}} </p>
                <p class="pStyle"> <span class="title">جنسیت : </span>{{profile.get_Gender_display}} </p>
                <p class="pStyle"> <span class="title">مقدار اعتبار : </span>{{profile.Credit}} </p>
            </div>
                <img src="{{ profile.ProfileImage.url }}" class="imageProf">

                <ul class="btnEdit">
                    <li><a class="btn btn-primary" href="/accounts/profileEdit">ویرایش پروفایل</a></li>
                </ul>
        </div>
        
    </div>
{% endblock %}   

accounts/templates/accounts/profileEdit.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
   ویرایش پروفایل 
{% endblock%}

{% block mainContent %}
    <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
        <div class="mainborder">
            <div class="row">
                <div class="col-md-10">
                    <div class="editBlock">
                        <p> <span class="title">نام : </span> {{userEditForm.first_name}}</p>
                        <p> <span class="title">نام خانوادگی : </span>{{userEditForm.last_name}}</p>
                        <p> <span class="title">ایمیل :</span> {{ userEditForm.email }} </p>
                        <p> <span class="title">جنسیت :</span> {{ profileEditForm.Gender }} </p>
                        <p> <span class="title">اعتبار : </span>{{ profileEditForm.Credit }} </p>
                            
                    </div>
                </div>     
                <div class="col-md-2">
                   <div class="imageBox">
                        <img src="{{ ProfileImage.url }}">
                   </div>
                   <p dir="rtl">تصویر پروفایل {{profileEditForm.ProfileImage}}</p>
                </div>
            </div>
            <div class="bottonborder">
                <button type="submit" class="btn btn-success">ذخیره</button>
            </div>
        </div>    
    </form>
{% endblock %}   

accounts/templates/accounts/profileRegister.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
   پروفایل {{concertdetails.Name}}
{% endblock%}

{% block mainContent %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="registerStyle">
            <div class="regData">
            <div class="row">
                <div class="col-md-6">
                    <p class="mylable">نام : {{ formData.first_name }} </p>
                    <p class="mylable">نام خانوادگی : {{ formData.last_name }} </p>
                    <p class="mylable">جنسیت : {{ formData.Gender }} </p>
                    <p class="mylable">اعتبار : {{ formData.Credit }} </p>
                        
                </div>
                <div class="col-md-6">
                    <p class="mylable">ایمیل : {{ formData.email }} </p>
                    <p class="mylable">نام کاربری : {{ formData.username }} </p>
                    <p class="mylable">رمز عبور : {{ formData.password }} </p>
                    <p class="mylable">  عکس :  {{ formData.ProfileImage }} </p>
                </div>
            </div>   
        </div>
        </div>
        <div class="bottonborder">
            <button type="submit" class="btn btn-success">ثبت نام</button>
        </div> 
        
    </form>
{% endblock %}   