concert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ticketSales.views import concertListView,locationListView,concertDetailsView,timeView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticketSales/',include('ticketSales.urls')),
    path('accounts/',include('accounts.urls'))


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ticketSales/urls.py
from django.urls import path
from ticketSales import views

urlpatterns = [
    path('concert/list', views.concertListView),
    path('location/list', views.locationListView),
    path('concert/<int:concert_id>',views.concertDetailsView),
    path('time/list', views.timeView),
    path('concertEdit/<int:concert_id>',views.concertEditView),
    path('sell_ticket/', views.sell_ticket_view),
]

ticketSales/models.py
from django.db import models
from jalali_date import date2jalali, datetime2jalali
from accounts.models import ProfileModel
# from accounts.models import ProfileModel
# Create your models here.

class concertModel(models.Model):

    class Meta:
        verbose_name="کنسرت"
        verbose_name_plural="کنسرت"


    Name = models.CharField(max_length=100, verbose_name="نام کنسرت")
    SingerName= models.CharField(max_length=100, verbose_name="نام خواننده")
    length=models.IntegerField(verbose_name="مدت زمان")
    Poster= models.ImageField(upload_to="concertImages/", verbose_name="پوستر")

    def __str__(self):
        return self.SingerName
    
    
class locationModel(models.Model):
    class Meta:
        verbose_name="محل برگزاری"
        verbose_name_plural="محل برگزاری"
    IdNumber=models.IntegerField(primary_key=True)
    Name=models.CharField(max_length=100, verbose_name="نام محل")    
    Address=models.CharField(max_length=500, default="تهران-برج میلاد",verbose_name="آدرس ")    
    Phone=models.CharField(max_length=11, null=True,verbose_name="تلفن ")    
    capacity=models.IntegerField(verbose_name="ظرفیت") 

    def __str__(self):
        return self.Name   

class timeModel(models.Model):
    class Meta:
        verbose_name="سانس"
        verbose_name_plural="سانس"

    concertModel= models.ForeignKey(concertModel,on_delete=models.PROTECT,verbose_name="کنسرت")
    locationModel = models.ForeignKey(locationModel, on_delete=models.PROTECT, verbose_name="محل برگزاری")
    StartDateTime = models.DateTimeField(verbose_name="زمان برگزاری")
    Seats = models.IntegerField(verbose_name="تعداد صندلی")

    Start=1
    End=2
    Cancle=3
    Soon=4
    status_choices=((Start,".فروش بلیط شروع شده است"),
                    (End, ".فروش بلیط تمام شده است"),
                    (Cancle, ".این سانس کنسل شده است"),
                    (Soon, ".فروش بلیط به زودی شروع خواهد شد")) 

    Status=models.IntegerField(choices=status_choices,verbose_name="وضعیت", null=True)   
    def __str__(self):
       return "Time: {} Singer: {} Location: {}".format(self.StartDateTime,self.concertModel.SingerName,self.locationModel.Address)
       
    def get_jalali_date(self):
        return datetime2jalali(self.StartDateTime)


class ticketModel(models.Model):
    class Meta:
        verbose_name="بلیط"
        verbose_name_plural="بلیط"    
    ProfileModel= models.ForeignKey(ProfileModel, on_delete= models.PROTECT,verbose_name="کاربر")
    timeModel= models.ForeignKey(timeModel, on_delete= models.PROTECT,verbose_name="سانس")
    TicketImage= models.ImageField(upload_to="TicketImages/",verbose_name="عکس")


    Name= models.CharField(max_length=100,verbose_name="عنوان")
    Price= models.IntegerField(verbose_name="مبلغ")

    def __str__(self):
        return "TicketInfo: Profile:{}".format(self.timeModel.__str__())
   

# class Seat(models.Model):
#     class Meta:
#         verbose_name="صندلی"
#         verbose_name_plural="صندلی"
#     seat_number = models.CharField(max_length=10)
#     is_reserved = models.BooleanField(default=False)

#     def ــstrــ(self):
#         return f"Seat {self.seat_number}"  

ticketSales/forms.py
from django import forms
from ticketSales.models import concertModel
from ticketSales.models import ticketModel

class SearchForm(forms.Form):
    SearchText=forms.CharField(max_length=100, label="نام کنسرت یا خواننده", required=False)

class ConcertForm(forms.ModelForm):
    class Meta:
        model= concertModel
        fields=['Name','SingerName','length', 'Poster']
        # exclude=["Poster"]

class TicketForm(forms.ModelForm):
    class Meta:
        model= ticketModel
        fields=['timeModel']
    name=forms.CharField(max_length=100, label="نام و نام خانوادگی", required=True)
    code=forms.CharField(max_length=10,label="کد ملی", required=True)

ticketSales/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from ticketSales.models import concertModel
from ticketSales.models import locationModel
from ticketSales.models import timeModel 
from django.urls import reverse
import ticketSales
import accounts
from django.contrib.auth.decorators import login_required
from ticketSales.forms import SearchForm, ConcertForm, TicketForm


# Create your views here.
def concertListView(request):

    searchForm=SearchForm(request.GET)
    if searchForm.is_valid():
        SearchText=searchForm.cleaned_data["SearchText"]
        concerts=concertModel.objects.filter(Name__contains=SearchText)
        concerts=concertModel.objects.filter(SingerName__contains=SearchText)


    else:
        concerts=concertModel.objects.all()

    context={
        "concertlist" : concerts,
        "concertcount" : concerts.count(),
        "searchForm" :searchForm
    }

    return render(request,"ticketSales/concertlist.html", context)

@login_required
def locationListView(request):
    locations=locationModel.objects.all()

    context={
        "location" : locations,
    }

    return render(request,"ticketSales/locationlist.html", context)

def concertDetailsView(request, concert_id):
    concert= concertModel.objects.get(pk=concert_id)

    context={
        "concertdetails": concert
    }
    return render(request,"ticketSales/concertDetails.html", context) 

@login_required
def timeView(request):   
    # if request.user.is_authenticated and request.user.is_active:
        times=timeModel.objects.all()

        context={
            "timelist": times,
        }
        return render(request,"ticketSales/timeList.html", context)
    # else:
        # return HttpResponseRedirect(reverse(accounts.views.loginView))

@login_required
def concertEditView(request, concert_id):
    concert= concertModel.objects.get(pk=concert_id)

    if request.method== "POST":
        concertForm=ConcertForm(request.POST, request.FILES, instance=concert)
        if concertForm.is_valid:
            concertForm.save()
            return HttpResponseRedirect(reverse(ticketSales.views.concertListView))
 
    else:
        concertForm=ConcertForm(instance=concert)

    context={
         "concertForm": concertForm,
         "PosterImage": concert.Poster
    }

    return render(request,"ticketSales/concertEdit.html", context)
    


def sell_ticket_view(request):
    if request.method=='POST':
        form = TicketForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('payment_url')
    else:
        form = TicketForm()
        return render(request,'ticketSales/sell_ticket.html', {'form': form})

ticketSales/templates/ticketSales/concertDetails.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
  جزئیات کنسرت
{% endblock%}

{% block mainContent %}

   <div class="col-md-10" dir="rtl">
      <h3 class="detailstyle"> نام کنسرت : {{ concertdetails.Name }}</h3>   
      <h3 class="detailstyle"> نام خواننده : {{ concertdetails.SingerName }}</h3>   
      <h3 class="detailstyle"> مدت زمان : {{ concertdetails.length }} دقیقه</h3> 
      <!-- <h3 class="detailstyle">محل برگزاری : {{timelist.locationModel.Address}}-{{timelist.locationModel.Name}} </h3>    -->
  

   </div>

   <div class="col-md-2">
      {% csrf_token %}
      <div class="imageBox">
         <img src="{{ concertdetails.Poster.url}}">
      </div>
      <a class="btn btn-success" href="/ticketSales/time/list">مشاهده سانس ها</a>
      <a href="/ticketSales/concertEdit/{{concertdetails.id}}" class="btn btn-success">ویرایش</a>

   </div>
{% endblock %}   

ticketSales/templates/ticketSales/concertEdit.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
   ویرایش کنسرت 
{% endblock%}

{% block mainContent %}
    
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ concertForm}} -->
        <div class="editForm">
            <div>
                <div">
                    <p>کنسرت: {{concertForm.Name}}</p>
                    <p>خواننده : {{concertForm.SingerName}}</p>
                    <p>مدت زمان: {{concertForm.length}}</p>
                </div>
                <div>
                    <div>
                        <img src="{{PosterImage.url}}"  class="imageEdit">
                    </div>
                   <p>تصویر کنسرت {{concertForm.Poster}}</p>
                </div>
            </div>
        </div>
        <div>
           <button type="submit" class="btn btn-success">ذخیره</button>
        </div>
    </form>
    
    
{% endblock%}
               

ticketSales/templates/ticketSales/concertlist.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
    لیست کنسرت ها
{% endblock%}

{% block mainContent %}
    {% if concertlist %}
        <form action="" method="GET" class="searchForm">
            <div class="search">
               {{searchForm }}
            </div>
            <div class="btnSearch">
            <button type="submit" class="btn btn-success">جستجو</button>
            </div>
        </form>

        {% for concert in concertlist %}
            <div class="col-md-4">
                <a href="/ticketSales/concert/{{ concert.id }}" class="astyle">
                    <div class="imageBox">
                        <img src="{{ concert.Poster.url }}">
                        {{ concert  }}
                    </div>
                </a>
            </div>
        {% endfor %}
    {% endif %}

{% endblock%}
               
           

ticketSales/templates/ticketSales/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>سامانه فروش بلیط کنسرت</title>
       
        <link rel="stylesheet" type="text/css" href="{% static 'ticketSales/css/bootstrap.css' %} " >
        <link rel="stylesheet" type="text/css" href="{% static 'ticketSales/css/fontawesome.css' %} " >
        <link rel="stylesheet" type="text/css" href="{% static 'ticketSales/css/style.css' %} " >
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400..700&family=Noto+Sans+Arabic:wght@100..900&display=swap" rel="stylesheet">

        <style>
            @font-face{
                font-family: 'IranianSans';
                src: local('IranianSans'),
                url('{% static "ticketSales/fonts/IranianSans/IranianSans.ttf" %}')format('ttf');
            }
        </style>
    </head>
    <body>
             
        <div class="container">
            <div class="row box">
               
                <h1 class="titlestyle">{% block titlepage %} {% endblock%}</h1>
                <ul class="btnul">
                    {% if user.is_authenticated %}
                        <li><a class="btn btn-success" href="/accounts/profile">پروفایل</a></li>
                        <li><a class="btn btn-danger" href="/accounts/logout">خروج</a></li>
                    {% else %}
                        <li><a class="btn btn-success" href="/accounts/login">ورود</a></li>
                        <li><a class="btn btn-danger" href="/accounts/profileRegister">ثبت نام</a></li>
                    {% endif %}
                                    
                    <li><a class="btn btn-success" href="/ticketSales/concert/list">صفحه اصلی</a></li>
                    <li><a class="btn btn-success" href="/ticketSales/time/list">مشاهده سانس های کنسرت</a></li>
                    <!-- <li><a class="btn btn-success" href="/ticketSales/location/list">اطلاعات محل</a></li> -->

                </ul>
            </div>
          
            <div class="row">
                
                  {% block mainContent %}{% endblock%}
               
            </div>
        </div>
          
    </body>
    <script src="{% static 'ticketSales/js/jquery-3.7.1.min.js' %} " ></script>
    <script src="{% static 'ticketSales/js/bootstrap.bundle.js' %} " ></script>
    <script src="{% static 'ticketSales/js/fontawesome.js' %} " ></script>
    <script src="{% static 'ticketSales/js/main.js' %} " ></script>
</html>

ticketSales/templates/ticketSales/locationList.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %}
   لیست مکان های برگزاری کنسرت
{% endblock %}

{% block mainContent %}

   <div class="row locationHeader">
      <div class="col-md-3">
         <h3>نام سالن</h3>
      </div>
      <div class="col-md-9">
            <h3>آدرس</h3>
      </div>
   </div>
    
   {% if locationlist%}
      {% for location in locationlist %}
         <div class="row location">
            <div class="col-md-2">
               {{location.Name}}
            </div>
            <div class="col-md-9">
               {{ location.Address }}
            </div>
         </div>
      {% endfor %}
   {% endif %}
{% endblock %}    

ticketSales/templates/ticketSales/sell_ticket.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %}
خرید بلیط
{% endblock %}

{% block mainContent %}
    <form method="POST" enctype="multipart/form-data" dir="rtl" style="margin-top: 20px;">
    {% csrf_token %}
       {{form.as_p}}
       <input type="submit" value="تایید" dir="rtl">
    </form>
{% endblock %}    

ticketSales/templates/ticketSales/ticket.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %}
خرید بلیط
{% endblock %}

{% block mainContent %}
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
    </form>
{% endblock %}    

ticketSales/templates/ticketSales/timeList.html
{% extends "ticketSales/layout.html" %}

{% block titlepage %} 
    لیست سانس ها
{% endblock%}

{% block mainContent %}
    {% if timelist %}
        {% for time in timelist %}
            <div class="col-md-4">
                <a>
                    <div class="timeBox">
                        <h3> {{ time.concertModel.Name }}</h3>
                        <p> {{ time.concertModel.SingerName }}</p>
                        <p> {{ time.locationModel.Address }}</p>                        
                        <p> {{ time.locationModel.Name }}</p>
                        <p> {{ time.get_jalali_date }}</p>


                        <div class="
                        {% if time.Status == time.Start %}
                            startbtn
                        {% elif time.Status == time.End %}
                            endbtn   
                        {% elif time.Status == time.Cancle %}
                            canclebtn
                        {% elif time.Status == time.Soon %}
                            soonbtn
 
                        {%endif%}
                        ">
                          
                            {{time.get_Status_display}}
                        </div>

                    </div>
                </a>
            </div>
        {% endfor %}
    {% endif %}

{% endblock%}
        